language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm
    - nightly
    - "7.0"



sudo: false



git:
    submodules: false



addons:
    apt:
        packages:
            #- php-codesniffer
            #- phpmd
            #- shellcheck



before_script:

    # Store all files in your own bin
    - mkdir bin
    - export PATH=$PATH:$PWD/bin/


    # Install validation tools
    #- npm install -g htmlhint csslint jshint jscs jsonlint js-yaml html-minifier@0.8.0 clean-css uglify-js
    
    # Install phpcs
    - curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
    - install --mode 0755 phpcs.phar $PWD/bin/phpcs

    # Install phpmd
    #- wget -c http://static.phpmd.org/php/latest/phpmd.phar
    #- install --mode 0755 phpmd.phar $PWD/bin/phpmd
    
    # Create a build directory for output
    - mkdir build



script:
    # Check versions of validation tools
    - node --version
    - npm --version
    
    #- htmlhint --version
    #- csslint --version
    #- jscs --version
    #- jshint --version
    - phpcs --version
    #- phpmd --version
    #- jsonlint --version
    #- js-yaml --version
    #- shellcheck --version
    
    #- html-minifier --version
    #- cleancss --version
    #- uglifyjs --version
    
    # Run validation & publish
    - make phpunit
    #- make phpcs



notifications:
    irc: "irc.freenode.org#dbwebb"

    webhooks:
        urls:
          - https://webhooks.gitter.im/e/cce29c69604daa8a60ab
        on_success: change  # options: [always|never|change] default: always
        on_failure: always  # options: [always|never|change] default: always
        on_start: never     # options: [always|never|change] default: always
